### ISSUE TITLE
launch node.js process via dumb-init

### ISSUE THREAD

**Issue by cmosetick** [carldanley/k8s-github-authenticator#1]
First off, thanks for this project. I realize it's a work in progress.

I built the project with your current Dockerfile and then ran a container from that image.
I noticed that you set the node process directly as the CMD, and thus I had to manually kill the container when I wanted to shutdown the container. (rather than issue the standard `ctrl-c` command)

My proposal is to use an init system such as `dumb-init` to launch the node.js process.
You can pull dumb-init into your image via a docker RUN command.
e.g.
`wget https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64`

OR

You could use a base image, with dumb-init and node already baked into the base image:
e.g.
`FROM cmosetick/alpine-dumb-init:node-8`

**Comment by carldanley** [comment]
@cmosetick First off: yes! This project is absolutely a WIP; I haven't had sufficient time yet to wrap my head around exactly where I want to take it but I will be putting together more documentation soon. That said, I'm excited to know there are other people out there with the same interest!

Secondly, great recommendations! I should have some time in the next day or two to PR this. I'm definitely 👍 though! If you get to it before I do, feel free to submit a PR.

Thanks for stumbling upon this project and taking the time to write!

**Comment by cmosetick** [comment]
Thanks very much @carldanley! Looking forward to the documentation for this project!

Here is a PR for what I proposed above:
https://github.com/carldanley/k8s-github-authenticator/pull/2

**Comment by cmosetick** [comment]
Saw your commit that uses my proposed Option1 above, so I just closed my PR. Thanks for your work here and still looking forward to the docs! 👍
